services:
  - type: web
    name: naver-map-rank
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app2.py --server.port=$PORT --server.address=0.0.0.0
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
  
  - type: cron
    name: naver-map-crawler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python crawler.py
    schedule: "0 6 * * *"  # 매일 오전 6시(UTC) = 한국 시간 오후 3시
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
