name: Naver Map Rank Crawler

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행 (UTC 기준)
  workflow_dispatch:  # 수동 실행 가능

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium==4.10.0
          pip install beautifulsoup4==4.11.0
          pip install pandas==2.0.0
          pip install webdriver-manager==3.8.0
          
      - name: Run crawler
        run: python crawler.py
        
      - name: Commit results
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/
          git commit -m "Update rank data $(date +'%Y-%m-%d')" || exit 0
          git push
